# Kernel Source for Vince (Redmi 5 Plus)
KERNEL_SOURCE=https://github.com/anandhan07/kernel_xiaomi_vince
KERNEL_SOURCE_BRANCH=master

# Kernel Config
KERNEL_CONFIG=vince-perf_defconfig

# Target Architecture
TARGET_ARCH=arm64

# Kernel Image Name
KERNEL_IMAGE_NAME=Image.gz-dtb

# KernelSU Settings
USE_KERNELSU=true
USE_KPROBES=true
USE_OVERLAYFS=true
DISABLE_LTO=true

# Boot Image Settings
MAKE_BOOT_IMAGE=true
SOURCE_BOOT_IMAGE=https://raw.githubusercontent.com/xiaoleGun/KernelSU_action/main/boot/boot-wayne-from-Miku-UI-latest.img
