# Kernel Source ( Vince 4.9 কার্নেল সোর্স )
KERNEL_SOURCE=https://github.com/anandhan07/kernel_xiaomi_vince
KERNEL_SOURCE_BRANCH=master

# Kernel Config ( Vince এর জন্য এটি সঠিক )
KERNEL_CONFIG=vince-perf_defconfig

# Target Architecture
TARGET_ARCH=arm64

# Kernel Image Name
KERNEL_IMAGE_NAME=Image.gz-dtb

# KernelSU যোগ করুন
USE_KERNELSU=true

# Kprobes চালু করুন (KernelSU Non-GKI এর জন্য দরকার)
USE_KPROBES=true

# Overlayfs চালু করুন
USE_OVERLAYFS=true

# LTO বন্ধ রাখুন (4.9 কার্নেলে LTO সমস্যা করতে পারে)
DISABLE_LTO=true

# Boot ইমেজ বানান
MAKE_BOOT_IMAGE=true

# সোর্স বুট ইমেজ (যেকোনো Vince এ কাস্টম রমের boot.img ব্যবহার করতে পারেন)
SOURCE_BOOT_IMAGE=https://raw.githubusercontent.com/xiaoleGun/KernelSU_action/main/boot/boot-wayne-from-Miku-UI-latest.img
